"""add image_url json

Revision ID: 5d61f870ef6f
Revises: 9bfbe4bfc1c7
Create Date: 2026-03-16 23:43:51.374511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5d61f870ef6f'
down_revision: Union[str, Sequence[str], None] = '9bfbe4bfc1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoes', sa.Column('image_url', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoes', 'image_url')
    # ### end Alembic commands ###
